// Every DOM element every feature module touches, queried once. ES modules can't let another
// module reassign an imported `let` binding, but they CAN mutate properties of an imported
// object -- so this is one object (`el`), filled in by `initDom()` before any feature's `init()`
// runs, instead of ~90 separate `const`s that used to all live in one function's closure.

export interface ElRefs {
  accountMenuEl: HTMLElement;
  accountButton: HTMLButtonElement;
  accountNameEl: HTMLElement;
  accountStatusEl: HTMLElement;
  accountMenuAccountsEl: HTMLElement;
  addOfflineMenuItem: HTMLButtonElement;
  manageAddOfflineBtn: HTMLButtonElement;
  playbarUserEl: HTMLElement;
  playButton: HTMLButtonElement;
  playLabelEl: HTMLElement;
  progressPanelEl: HTMLElement;
  progressLabelEl: HTMLElement;
  progressPercentEl: HTMLElement;
  progressFillEl: HTMLElement;
  launchErrorEl: HTMLElement;
  loginModalEl: HTMLElement;
  loginCodeEl: HTMLElement;
  errorModalEl: HTMLElement;
  errorMessageEl: HTMLElement;
  offlineModalEl: HTMLElement;
  offlineModalEyebrowEl: HTMLElement;
  offlineNicknameInput: HTMLInputElement;
  offlineNicknameError: HTMLElement;
  offlineConfirmBtn: HTMLButtonElement;
  accountsScreenEl: HTMLElement;
  settingsScreenEl: HTMLElement;
  instanceScreenEl: HTMLElement;
  accountsNavBtn: HTMLButtonElement;
  accountsBackBtn: HTMLButtonElement;
  manageListEl: HTMLElement;
  settingsNavBtn: HTMLButtonElement;
  settingsBackBtn: HTMLButtonElement;
  snapshotsToggle: HTMLButtonElement;
  snapshotsToggleLabel: HTMLElement;
  screenshotsBgToggle: HTMLButtonElement;
  screenshotsBgToggleLabel: HTMLElement;
  screenshotsBgBlurInput: HTMLInputElement;
  gameDirPathEl: HTMLElement;
  gameDirOpenBtn: HTMLButtonElement;
  gameDirBrowseBtn: HTMLButtonElement;
  instancesDirPathEl: HTMLElement;
  instancesDirOpenBtn: HTMLButtonElement;
  instancesDirBrowseBtn: HTMLButtonElement;
  configDirPathEl: HTMLElement;
  configDirOpenBtn: HTMLButtonElement;
  themeOptions: NodeListOf<HTMLButtonElement>;
  skinsSigninEl: HTMLElement;
  skinsSigninBtn: HTMLButtonElement;
  skinsViewEl: HTMLElement;
  skinViewerCanvas: HTMLCanvasElement;
  skinVariantOptions: NodeListOf<HTMLButtonElement>;
  skinUploadBtn: HTMLButtonElement;
  skinResetBtn: HTMLButtonElement;
  skinsRefreshBtn: HTMLButtonElement;
  capeGridEl: HTMLElement;
  wipeAllBtn: HTMLButtonElement;
  wipeModalEl: HTMLElement;
  wipeConfirmInput: HTMLInputElement;
  wipeConfirmBtn: HTMLButtonElement;
  wipeCancelBtn: HTMLButtonElement;
  heroEl: HTMLElement;
  heroBackdropAEl: HTMLElement;
  heroBackdropBEl: HTMLElement;
  instancePickerEl: HTMLElement;
  instancePickerTrigger: HTMLButtonElement;
  instancePickerIconEl: HTMLElement;
  instancePickerListEl: HTMLElement;
  playbarInstanceNameEl: HTMLElement;
  playbarInstanceVersionEl: HTMLElement;
  instanceGridEl: HTMLElement;
  newInstanceBtn: HTMLButtonElement;
  importInstanceBtn: HTMLButtonElement;
  instanceBackBtn: HTMLButtonElement;
  instanceScreenTitleEl: HTMLElement;
  instanceIconBtn: HTMLButtonElement;
  instanceDetailNameEl: HTMLElement;
  instanceDetailVersionEl: HTMLElement;
  instanceVersionNameEl: HTMLElement;
  instancePlayPauseBtn: HTMLButtonElement;
  instanceLaunchErrorEl: HTMLElement;
  advancedLogOutputEl: HTMLElement;
  advancedLogClearBtn: HTMLButtonElement;
  instanceRenameBtn: HTMLButtonElement;
  instanceVersionBtn: HTMLButtonElement;
  instanceIconClearBtn: HTMLButtonElement;
  instanceOpenFolderBtn: HTMLButtonElement;
  instanceLibrariesOpenBtn: HTMLButtonElement;
  instanceExportBtn: HTMLButtonElement;
  instanceDeleteBtn: HTMLButtonElement;
  instanceOverflowMenuEl: HTMLElement;
  instanceOverflowBtn: HTMLButtonElement;
  modsListEl: HTMLElement;
  modsAddBtn: HTMLButtonElement;
  modsDeleteBtn: HTMLButtonElement;
  modsOpenFolderBtn: HTMLButtonElement;
  worldsListEl: HTMLElement;
  worldsOpenFolderBtn: HTMLButtonElement;
  resourcePacksListEl: HTMLElement;
  resourcePacksOpenFolderBtn: HTMLButtonElement;
  resourcePacksBrowseBtn: HTMLButtonElement;
  shaderPacksListEl: HTMLElement;
  shaderPacksOpenFolderBtn: HTMLButtonElement;
  shaderPacksBrowseBtn: HTMLButtonElement;
  screenshotsGridEl: HTMLElement;
  screenshotsOpenFolderBtn: HTMLButtonElement;
  createInstanceModalEl: HTMLElement;
  createInstanceNameInput: HTMLInputElement;
  createInstanceVersionsEl: HTMLElement;
  createInstanceErrorEl: HTMLElement;
  createInstanceConfirmBtn: HTMLButtonElement;
  createInstanceCancelBtn: HTMLButtonElement;
  changeVersionModalEl: HTMLElement;
  changeVersionVersionsEl: HTMLElement;
  changeVersionCancelBtn: HTMLButtonElement;
  instanceLoaderNameEl: HTMLElement;
  instanceLoaderInstallBtn: HTMLButtonElement;
  instanceLoaderRemoveBtn: HTMLButtonElement;
  installLoaderModalEl: HTMLElement;
  loaderKindOptions: NodeListOf<HTMLButtonElement>;
  installLoaderVersionsEl: HTMLElement;
  installLoaderErrorEl: HTMLElement;
  installLoaderProgressEl: HTMLElement;
  installLoaderProgressLabelEl: HTMLElement;
  installLoaderProgressPercentEl: HTMLElement;
  installLoaderProgressFillEl: HTMLElement;
  installLoaderConfirmBtn: HTMLButtonElement;
  installLoaderCancelBtn: HTMLButtonElement;
  modsBrowseBtn: HTMLButtonElement;
  browseModsModalEl: HTMLElement;
  browseModsEyebrowEl: HTMLElement;
  modSourceOptions: NodeListOf<HTMLButtonElement>;
  modSourceCurseForgeBtn: HTMLButtonElement;
  browseModsQueryInput: HTMLInputElement;
  browseModsHintEl: HTMLElement;
  browseModsResultsEl: HTMLElement;
  browseModsErrorEl: HTMLElement;
  browseModsCloseBtn: HTMLButtonElement;
  browseModsReviewBtn: HTMLButtonElement;
  modDetailPaneEl: HTMLElement;
  modDetailPlaceholderEl: HTMLElement;
  modDetailContentEl: HTMLElement;
  modDetailTitleEl: HTMLElement;
  modDetailMetaEl: HTMLElement;
  modDetailBodyEl: HTMLElement;
  reviewModsModalEl: HTMLElement;
  reviewModsListEl: HTMLElement;
  reviewModsErrorEl: HTMLElement;
  reviewModsProgressEl: HTMLElement;
  reviewModsProgressLabelEl: HTMLElement;
  reviewModsProgressPercentEl: HTMLElement;
  reviewModsProgressFillEl: HTMLElement;
  reviewModsConfirmBtn: HTMLButtonElement;
  reviewModsCancelBtn: HTMLButtonElement;
  curseforgeKeyStatusEl: HTMLElement;
  curseforgeKeyInput: HTMLInputElement;
  curseforgeKeySaveBtn: HTMLButtonElement;
  curseforgeKeyClearBtn: HTMLButtonElement;
  curseforgeKeyRequestBtn: HTMLButtonElement;
  renameInstanceModalEl: HTMLElement;
  renameInstanceInput: HTMLInputElement;
  renameInstanceErrorEl: HTMLElement;
  renameInstanceConfirmBtn: HTMLButtonElement;
  renameInstanceCancelBtn: HTMLButtonElement;
  confirmModalEl: HTMLElement;
  confirmEyebrowEl: HTMLElement;
  confirmMessageEl: HTMLElement;
  confirmActionBtn: HTMLButtonElement;
  confirmCancelBtn: HTMLButtonElement;
  loginOpenBrowserBtn: HTMLButtonElement;
  loginCloseBtn: HTMLButtonElement;
  errorCloseBtn: HTMLButtonElement;
  offlineCancelBtn: HTMLButtonElement;
  manageAddMicrosoftBtn: HTMLButtonElement;
  accountMenuSigninBtn: HTMLButtonElement;
  accountMenuAddOfflineBtn: HTMLButtonElement;
  accountMenuManageBtn: HTMLButtonElement;
}

export const el = {} as ElRefs;

function q<T extends Element>(selector: string): T {
  return document.querySelector<T>(selector)!;
}

/// Fills in every field of `el`. Must run before any feature module's `init()` -- same ordering
/// requirement today's single `main()` already had (every `const` was queried before any
/// `addEventListener` call that used it).
export function initDom() {
  Object.assign<ElRefs, ElRefs>(el, {
    accountMenuEl: q("#account-menu"),
    accountButton: q("#account-button"),
    accountNameEl: q("#account-name"),
    accountStatusEl: q("#account-status"),
    accountMenuAccountsEl: q("#account-menu-accounts"),
    addOfflineMenuItem: q("#account-menu-add-offline"),
    manageAddOfflineBtn: q("#manage-add-offline"),
    playbarUserEl: q("#playbar-user"),
    playButton: q("#play-button"),
    playLabelEl: q("#play-label"),
    progressPanelEl: q("#progress-panel"),
    progressLabelEl: q("#progress-label"),
    progressPercentEl: q("#progress-percent"),
    progressFillEl: q("#progress-fill"),
    launchErrorEl: q("#launch-error"),
    loginModalEl: q("#login-modal"),
    loginCodeEl: q("#login-code"),
    errorModalEl: q("#error-modal"),
    errorMessageEl: q("#error-message"),
    offlineModalEl: q("#offline-modal"),
    offlineModalEyebrowEl: q("#offline-modal-eyebrow"),
    offlineNicknameInput: q("#offline-nickname-input"),
    offlineNicknameError: q("#offline-nickname-error"),
    offlineConfirmBtn: q("#offline-confirm"),
    accountsScreenEl: q("#accounts-screen"),
    settingsScreenEl: q("#settings-screen"),
    instanceScreenEl: q("#instance-screen"),
    accountsNavBtn: q("#accounts-nav"),
    accountsBackBtn: q("#accounts-back"),
    manageListEl: q("#manage-list"),
    settingsNavBtn: q("#settings-nav"),
    settingsBackBtn: q("#settings-back"),
    snapshotsToggle: q("#snapshots-toggle"),
    snapshotsToggleLabel: q("#snapshots-toggle-label"),
    screenshotsBgToggle: q("#screenshots-bg-toggle"),
    screenshotsBgToggleLabel: q("#screenshots-bg-toggle-label"),
    screenshotsBgBlurInput: q("#screenshots-bg-blur"),
    gameDirPathEl: q("#game-dir-path"),
    gameDirOpenBtn: q("#game-dir-open"),
    gameDirBrowseBtn: q("#game-dir-browse"),
    instancesDirPathEl: q("#instances-dir-path"),
    instancesDirOpenBtn: q("#instances-dir-open"),
    instancesDirBrowseBtn: q("#instances-dir-browse"),
    configDirPathEl: q("#config-dir-path"),
    configDirOpenBtn: q("#config-dir-open"),
    themeOptions: document.querySelectorAll<HTMLButtonElement>(".theme-option"),
    skinsSigninEl: q("#skins-signin"),
    skinsSigninBtn: q("#skins-signin-btn"),
    skinsViewEl: q("#skins-view"),
    skinViewerCanvas: q("#skin-viewer-canvas"),
    skinVariantOptions: document.querySelectorAll<HTMLButtonElement>(".skin-variant__option"),
    skinUploadBtn: q("#skin-upload-btn"),
    skinResetBtn: q("#skin-reset-btn"),
    skinsRefreshBtn: q("#skins-refresh-btn"),
    capeGridEl: q("#cape-grid"),
    wipeAllBtn: q("#wipe-all-btn"),
    wipeModalEl: q("#wipe-modal"),
    wipeConfirmInput: q("#wipe-confirm-input"),
    wipeConfirmBtn: q("#wipe-confirm-btn"),
    wipeCancelBtn: q("#wipe-cancel-btn"),
    heroEl: q("#hero"),
    heroBackdropAEl: q("#hero-backdrop-a"),
    heroBackdropBEl: q("#hero-backdrop-b"),
    instancePickerEl: q("#instance-picker"),
    instancePickerTrigger: q("#instance-picker-trigger"),
    instancePickerIconEl: q("#instance-picker-icon"),
    instancePickerListEl: q("#instance-picker-list"),
    playbarInstanceNameEl: q("#playbar-instance-name"),
    playbarInstanceVersionEl: q("#playbar-instance-version"),
    instanceGridEl: q("#instance-grid"),
    newInstanceBtn: q("#new-instance-btn"),
    importInstanceBtn: q("#import-instance-btn"),
    instanceBackBtn: q("#instance-back"),
    instanceScreenTitleEl: q("#instance-screen-title"),
    instanceIconBtn: q("#instance-icon-btn"),
    instanceDetailNameEl: q("#instance-detail-name"),
    instanceDetailVersionEl: q("#instance-detail-version"),
    instanceVersionNameEl: q("#instance-version-name"),
    instancePlayPauseBtn: q("#instance-playpause-btn"),
    instanceLaunchErrorEl: q("#instance-launch-error"),
    advancedLogOutputEl: q("#advanced-log-output"),
    advancedLogClearBtn: q("#advanced-log-clear-btn"),
    instanceRenameBtn: q("#instance-rename-btn"),
    instanceVersionBtn: q("#instance-version-btn"),
    instanceIconClearBtn: q("#instance-icon-clear-btn"),
    instanceOpenFolderBtn: q("#instance-open-folder-btn"),
    instanceLibrariesOpenBtn: q("#instance-libraries-open-btn"),
    instanceExportBtn: q("#instance-export-btn"),
    instanceDeleteBtn: q("#instance-delete-btn"),
    instanceOverflowMenuEl: q("#instance-overflow-menu"),
    instanceOverflowBtn: q("#instance-overflow-btn"),
    modsListEl: q("#mods-list"),
    modsAddBtn: q("#mods-add-btn"),
    modsDeleteBtn: q("#mods-delete-btn"),
    modsOpenFolderBtn: q("#mods-open-folder-btn"),
    worldsListEl: q("#worlds-list"),
    worldsOpenFolderBtn: q("#worlds-open-folder-btn"),
    resourcePacksListEl: q("#resource-packs-list"),
    resourcePacksOpenFolderBtn: q("#resource-packs-open-folder-btn"),
    resourcePacksBrowseBtn: q("#resource-packs-browse-btn"),
    shaderPacksListEl: q("#shader-packs-list"),
    shaderPacksOpenFolderBtn: q("#shader-packs-open-folder-btn"),
    shaderPacksBrowseBtn: q("#shader-packs-browse-btn"),
    screenshotsGridEl: q("#screenshots-grid"),
    screenshotsOpenFolderBtn: q("#screenshots-open-folder-btn"),
    createInstanceModalEl: q("#create-instance-modal"),
    createInstanceNameInput: q("#create-instance-name"),
    createInstanceVersionsEl: q("#create-instance-versions"),
    createInstanceErrorEl: q("#create-instance-error"),
    createInstanceConfirmBtn: q("#create-instance-confirm"),
    createInstanceCancelBtn: q("#create-instance-cancel"),
    changeVersionModalEl: q("#change-version-modal"),
    changeVersionVersionsEl: q("#change-version-versions"),
    changeVersionCancelBtn: q("#change-version-cancel"),
    instanceLoaderNameEl: q("#instance-loader-name"),
    instanceLoaderInstallBtn: q("#instance-loader-install-btn"),
    instanceLoaderRemoveBtn: q("#instance-loader-remove-btn"),
    installLoaderModalEl: q("#install-loader-modal"),
    loaderKindOptions: document.querySelectorAll<HTMLButtonElement>("#loader-kind-options .skin-variant__option"),
    installLoaderVersionsEl: q("#install-loader-versions"),
    installLoaderErrorEl: q("#install-loader-error"),
    installLoaderProgressEl: q("#install-loader-progress"),
    installLoaderProgressLabelEl: q("#install-loader-progress-label"),
    installLoaderProgressPercentEl: q("#install-loader-progress-percent"),
    installLoaderProgressFillEl: q("#install-loader-progress-fill"),
    installLoaderConfirmBtn: q("#install-loader-confirm"),
    installLoaderCancelBtn: q("#install-loader-cancel"),
    modsBrowseBtn: q("#mods-browse-btn"),
    browseModsModalEl: q("#browse-mods-modal"),
    browseModsEyebrowEl: q("#browse-mods-eyebrow"),
    modSourceOptions: document.querySelectorAll<HTMLButtonElement>("#mod-source-options .skin-variant__option"),
    modSourceCurseForgeBtn: q("#mod-source-curseforge"),
    browseModsQueryInput: q("#browse-mods-query"),
    browseModsHintEl: q("#browse-mods-hint"),
    browseModsResultsEl: q("#browse-mods-results"),
    browseModsErrorEl: q("#browse-mods-error"),
    browseModsCloseBtn: q("#browse-mods-close"),
    browseModsReviewBtn: q("#browse-mods-review-btn"),
    modDetailPaneEl: q("#mod-detail-pane"),
    modDetailPlaceholderEl: q("#mod-detail-placeholder"),
    modDetailContentEl: q("#mod-detail-content"),
    modDetailTitleEl: q("#mod-detail-title"),
    modDetailMetaEl: q("#mod-detail-meta"),
    modDetailBodyEl: q("#mod-detail-body"),
    reviewModsModalEl: q("#review-mods-modal"),
    reviewModsListEl: q("#review-mods-list"),
    reviewModsErrorEl: q("#review-mods-error"),
    reviewModsProgressEl: q("#review-mods-progress"),
    reviewModsProgressLabelEl: q("#review-mods-progress-label"),
    reviewModsProgressPercentEl: q("#review-mods-progress-percent"),
    reviewModsProgressFillEl: q("#review-mods-progress-fill"),
    reviewModsConfirmBtn: q("#review-mods-confirm"),
    reviewModsCancelBtn: q("#review-mods-cancel"),
    curseforgeKeyStatusEl: q("#curseforge-key-status"),
    curseforgeKeyInput: q("#curseforge-key-input"),
    curseforgeKeySaveBtn: q("#curseforge-key-save"),
    curseforgeKeyClearBtn: q("#curseforge-key-clear"),
    curseforgeKeyRequestBtn: q("#curseforge-key-request"),
    renameInstanceModalEl: q("#rename-instance-modal"),
    renameInstanceInput: q("#rename-instance-input"),
    renameInstanceErrorEl: q("#rename-instance-error"),
    renameInstanceConfirmBtn: q("#rename-instance-confirm"),
    renameInstanceCancelBtn: q("#rename-instance-cancel"),
    confirmModalEl: q("#delete-instance-modal"),
    confirmEyebrowEl: q("#delete-instance-eyebrow"),
    confirmMessageEl: q("#delete-instance-message"),
    confirmActionBtn: q("#delete-instance-confirm"),
    confirmCancelBtn: q("#delete-instance-cancel"),
    loginOpenBrowserBtn: q("#login-open-browser"),
    loginCloseBtn: q("#login-close"),
    errorCloseBtn: q("#error-close"),
    offlineCancelBtn: q("#offline-cancel"),
    manageAddMicrosoftBtn: q("#manage-add-microsoft"),
    accountMenuSigninBtn: q("#account-menu-signin"),
    accountMenuAddOfflineBtn: q("#account-menu-add-offline"),
    accountMenuManageBtn: q("#account-menu-manage"),
  });
}
